### ISSUE TITLE
Update to ScanInternal from GuidedHacking

### ISSUE THREAD

**Issue by towbes** [Erarnitox/TeraProxy#3]
Hi Erarnitox, just wanted to say thanks for the great tutorial and source code.  I'm working on something similar for DAOC: https://github.com/towbes/daoc-logger  (haven't updated the readme yet but i'm now using your framework for actually hooking unencrypted not just using detours library.

I ran into issues calling ScanInternal probably because I wasn't using the right address range.  I took the opportunity to use the "Internal Module Scan Wrapper​" part from https://guidedhacking.com/threads/external-internal-pattern-scanning-guide.14112/ which makes an easier call of just ScanInternal(pattern, mask, "module.dll") to get rid of the issue having to find the address range.  Might be something to consider refactoring here

**Comment by Erarnitox** [comment]
Hey, glad you liked the tutorial and congrats on your Packet Editor!

Thanks for the suggestion, but I won't implement that for my proxy and here is why:
- having a range can significantly lower the scan time for large modules, as you only need to scan  a small range of the module as you know the code you are looking for is very likely in a certain range.
- It is more flexible. And you can easily write a wrapper to make easier calls like the one you described possible. As you need the address of the module you want to search in anyways, you can call it like `ScanInternal(pattern, mask, module_base, module_base+module_size)`

Also know why I have used this function in the first place: The game got frequently updated when I was developing this and I got tired of searching the correct addresses after each update. In your case for Dark Age of Camelot, I don't think the game gets updated to frequently anymore, so you should be fine hard coding the offsets.

You are certainly right that there is quite a few things that can be solved more elegantly, safer or more performant, but for right now I see this project as "done". However, I might come back to that at some later point and apply it to another game or program and fix some things along the way.

Thanks a lot for reading the guide and suggesting changes, really appreciated!
Your project does also look good! you might consider adding your own name in the title there haha.

Also for improvements: check the comments in the guidedhacking thread, there where some good suggestions

I will close this issue here, but feel free to make new ones (might take ages for me to implement as this project is not at any priority for me right now)
